### ISSUE TITLE
Manifest causing 500 error when testing 3.0

### ISSUE THREAD

**Issue by glenrobson** [IIIF/presentation-validator#97]
The following manifest is causing a 500 error on the validator:

https://purl.stanford.edu/hg676jb4964/iiif3/manifest

Version 3.0, full URL:

https://iiif.io/api/presentation/validator/service/validate?format=json&version=3.0&url=https://purl.stanford.edu/hg676jb4964/iiif3/manifest

**Comment by glenrobson** [comment]
Exception:

```
Validation Failed
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "iiif-presentation-validator.py", line 153, in do_GET_test
    return self.check_manifest(data, version, url, warnings)
  File "iiif-presentation-validator.py", line 67, in check_manifest
    infojson = schemavalidator.validate(data, version, url)
  File "/Users/gmr/development/iiif/presentation-validator/schema/schemavalidator.py", line 65, in validate
    err = errorParser.diagnoseWhichOneOf(list(err.absolute_schema_path), list(err.absolute_path))
  File "/Users/gmr/development/iiif/presentation-validator/schema/error_processor.py", line 122, in diagnoseWhichOneOf
    store_errs.append(self.diagnoseWhichOneOf(error_path, IIIFJsonPath)) # so recursivly discovery real error
  File "/Users/gmr/development/iiif/presentation-validator/schema/error_processor.py", line 80, in diagnoseWhichOneOf
    schema_part = self.addReferences(self.getSchemaPortion(error_path))
  File "/Users/gmr/development/iiif/presentation-validator/schema/error_processor.py", line 174, in getSchemaPortion
    if isinstance(schemaEl[pathPart], dict) and "$ref" in schemaEl[pathPart]:
KeyError: 'oneOf'
```
